[[Arb]]
arch = "aarch64"
git-tree-sha1 = "e8d5af2ae8fab7bf59bafccb8ff4de81b7cb7d55"
libc = "glibc"
os = "linux"

    [[Arb.download]]
    sha256 = "cda3a7c322da3f838e3465ec0a557972db540029c734a486380f385a00653c3b"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.18.1+0/Arb.v2.18.1.aarch64-linux-gnu.tar.gz"
[[Arb]]
arch = "aarch64"
git-tree-sha1 = "9d8992fffb7c8a0c2483c479fb9bd0fb56aedd69"
libc = "musl"
os = "linux"

    [[Arb.download]]
    sha256 = "219f72d7a49fe32d32094bd14ee0c79eaa268f14156690162072def6e9870c8f"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.18.1+0/Arb.v2.18.1.aarch64-linux-musl.tar.gz"
[[Arb]]
arch = "armv7l"
git-tree-sha1 = "b0aca3237e283d53897ce00756891a3a3c13d732"
libc = "glibc"
os = "linux"

    [[Arb.download]]
    sha256 = "e7114f30691449db5b1fd9e8eb8507450baacf4a975d1a51d35aed28ba225e50"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.18.1+0/Arb.v2.18.1.armv7l-linux-gnueabihf.tar.gz"
[[Arb]]
arch = "armv7l"
git-tree-sha1 = "c16fa83372b0ce0f8151855ae3c2486ec19a5404"
libc = "musl"
os = "linux"

    [[Arb.download]]
    sha256 = "27ec0e8b67fdf92a7a49bbdd4f511af212b44824e3b5fe76a9ebee8ce0cf0b41"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.18.1+0/Arb.v2.18.1.armv7l-linux-musleabihf.tar.gz"
[[Arb]]
arch = "i686"
git-tree-sha1 = "d175545d067b34342c1d93c1edf73581612a53e3"
libc = "glibc"
os = "linux"

    [[Arb.download]]
    sha256 = "7a0d39b2636e75e888b748c04f095c65a70478314195767c39d3f6d6cc90dc88"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.18.1+0/Arb.v2.18.1.i686-linux-gnu.tar.gz"
[[Arb]]
arch = "i686"
git-tree-sha1 = "c707fb9bf66ee518d6ffb7b2551c704056601105"
libc = "musl"
os = "linux"

    [[Arb.download]]
    sha256 = "208bb19e8625c51ca80e7fc993e202cab28326b4e6674fa4af1c50961fd94926"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.18.1+0/Arb.v2.18.1.i686-linux-musl.tar.gz"
[[Arb]]
arch = "i686"
git-tree-sha1 = "e384c4503209dee243a9f12fcede47cafdd4da7a"
os = "windows"

    [[Arb.download]]
    sha256 = "8beecf6f210683f307bffefca4fd9045416ff1743b51606d58503481802675a3"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.18.1+0/Arb.v2.18.1.i686-w64-mingw32.tar.gz"
[[Arb]]
arch = "powerpc64le"
git-tree-sha1 = "3829c1b4c87ee46cf935354f1b04ea8cc0be1625"
libc = "glibc"
os = "linux"

    [[Arb.download]]
    sha256 = "50d8e5e8ee79e9eff9ae1225531fdcf40b7af20d395546f89fbc6e0c8ff1a35b"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.18.1+0/Arb.v2.18.1.powerpc64le-linux-gnu.tar.gz"
[[Arb]]
arch = "x86_64"
git-tree-sha1 = "ddb3fe2bd525c675f14cc3ec2afb5c943dda93a0"
os = "macos"

    [[Arb.download]]
    sha256 = "a58dcf334c899aacee8c07ba05dc9611da1ae4b9dcf92353fd8c8eaa9f3dd6e5"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.18.1+0/Arb.v2.18.1.x86_64-apple-darwin14.tar.gz"
[[Arb]]
arch = "x86_64"
git-tree-sha1 = "1f4e5762991b4f836993de3fc70599603880c0da"
libc = "glibc"
os = "linux"

    [[Arb.download]]
    sha256 = "7067b9b3ad2e7abab39e96e004dafa92e8ebf1d8132cc1c125b00f03b47c1f8b"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.18.1+0/Arb.v2.18.1.x86_64-linux-gnu.tar.gz"
[[Arb]]
arch = "x86_64"
git-tree-sha1 = "3f593caa7924bc8b016ead3b019b1f9383af2fb3"
libc = "musl"
os = "linux"

    [[Arb.download]]
    sha256 = "7aa1fa4ed6b4b5557fb6508a8e292b4b8c0a51c189b87d51f6f55ffee2dfbb8d"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.18.1+0/Arb.v2.18.1.x86_64-linux-musl.tar.gz"
[[Arb]]
arch = "x86_64"
git-tree-sha1 = "5afb378241d77e118197ad198b7f655560d36eee"
os = "freebsd"

    [[Arb.download]]
    sha256 = "a73cfb546436bca00b87818902494c656362acf92ac21bdc072a6b05663b7402"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.18.1+0/Arb.v2.18.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Arb]]
arch = "x86_64"
git-tree-sha1 = "41af58daba06566c43b8025900898bc7f6b8ecb3"
os = "windows"

    [[Arb.download]]
    sha256 = "1e889e8d814008e6a1e8f2a7d2dae1e0da3a692f4082e0c9c5a1b564f9e1c9f5"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.18.1+0/Arb.v2.18.1.x86_64-w64-mingw32.tar.gz"
