[[Arb]]
arch = "aarch64"
git-tree-sha1 = "ed7834fe9feb3c2b095502777b180037360531db"
libc = "glibc"
os = "linux"

    [[Arb.download]]
    sha256 = "6f1d481d54974ea2f602999f4fbaeabfecce9b5a54d83d60da84bcf118ad232a"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.17.0+1/Arb.v2.17.0.aarch64-linux-gnu.tar.gz"
[[Arb]]
arch = "aarch64"
git-tree-sha1 = "18f51bbf90b4cd8b1a4e06bdf376750eda35467d"
libc = "musl"
os = "linux"

    [[Arb.download]]
    sha256 = "a70107d7f945011070264d8ba92aa85323672ed9d647a59a56636edcbe3b134d"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.17.0+1/Arb.v2.17.0.aarch64-linux-musl.tar.gz"
[[Arb]]
arch = "armv7l"
git-tree-sha1 = "c76b7f18eff9f8aed03bb93db3f65ffebe48ff02"
libc = "glibc"
os = "linux"

    [[Arb.download]]
    sha256 = "c67578d24c4057121ccf43185d6c237203314e553084a6d051d31c948a5f12d8"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.17.0+1/Arb.v2.17.0.armv7l-linux-gnueabihf.tar.gz"
[[Arb]]
arch = "armv7l"
git-tree-sha1 = "536e0452de79aba620a5a34140ff7deda0b6a2da"
libc = "musl"
os = "linux"

    [[Arb.download]]
    sha256 = "7295ea554044d2d0d1bbbc594f6ea33b1e749d48c12e0559b6d2ae6ca1430c57"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.17.0+1/Arb.v2.17.0.armv7l-linux-musleabihf.tar.gz"
[[Arb]]
arch = "i686"
git-tree-sha1 = "b799e1134265f5804cbcecdf36400babb2abd3ac"
libc = "glibc"
os = "linux"

    [[Arb.download]]
    sha256 = "9e5ea805acc70db27b761607b542e1d8d776223edd5417125a9004d3b6158fb4"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.17.0+1/Arb.v2.17.0.i686-linux-gnu.tar.gz"
[[Arb]]
arch = "i686"
git-tree-sha1 = "3b66febde9bbdc7ad1b70851c7c1938f546cd2f5"
libc = "musl"
os = "linux"

    [[Arb.download]]
    sha256 = "2035ada8c24a38921af16aa66a924990e7814ffaba27507dee507761962bfd29"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.17.0+1/Arb.v2.17.0.i686-linux-musl.tar.gz"
[[Arb]]
arch = "i686"
git-tree-sha1 = "0f15b54c86654a68ab5aa2148a92e73961f80e9b"
os = "windows"

    [[Arb.download]]
    sha256 = "c5643ebaefe4d5fc5e8026cdd6aff06c63dec8c7dd86d421ecf0ee4f8900a581"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.17.0+1/Arb.v2.17.0.i686-w64-mingw32.tar.gz"
[[Arb]]
arch = "powerpc64le"
git-tree-sha1 = "d2e397e4e8dfdbdcbbcf2d82e7f2144afeef1ccd"
libc = "glibc"
os = "linux"

    [[Arb.download]]
    sha256 = "d7a05ae54bc078917afecf2e871ef48c55148b36e9e5bc35b4788aaa4faa2113"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.17.0+1/Arb.v2.17.0.powerpc64le-linux-gnu.tar.gz"
[[Arb]]
arch = "x86_64"
git-tree-sha1 = "75ae1f6601912e0cc4f3e8cb4ca2e6530628360c"
os = "macos"

    [[Arb.download]]
    sha256 = "535e90c1dbab3c0122e9539a5f79176582d2256c2c839b5879c9e9f8ef4e5ed8"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.17.0+1/Arb.v2.17.0.x86_64-apple-darwin14.tar.gz"
[[Arb]]
arch = "x86_64"
git-tree-sha1 = "758af0b6598417bda130976fa2ddfa3bb257cc0f"
libc = "glibc"
os = "linux"

    [[Arb.download]]
    sha256 = "edae546e3af250a3642895c7cb3654ab797815c3f7a0877a8e0c38bc0aa1b1a5"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.17.0+1/Arb.v2.17.0.x86_64-linux-gnu.tar.gz"
[[Arb]]
arch = "x86_64"
git-tree-sha1 = "660e8d98d6ff9ce4c008329f85f68e34244b5e27"
libc = "musl"
os = "linux"

    [[Arb.download]]
    sha256 = "36daa4dab00a60a768a34313ce29985eb37cc833027bc856bfa68b79cfcc1404"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.17.0+1/Arb.v2.17.0.x86_64-linux-musl.tar.gz"
[[Arb]]
arch = "x86_64"
git-tree-sha1 = "08c84eec377666ffa183580e57aff6465c5008b9"
os = "freebsd"

    [[Arb.download]]
    sha256 = "4987691cc15676927462c3cd174e9a9d35c12ca9203096d6387a7d2bb3ac2f91"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.17.0+1/Arb.v2.17.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Arb]]
arch = "x86_64"
git-tree-sha1 = "a72a0f01d6e6125699a944da0be73017f9d9020c"
os = "windows"

    [[Arb.download]]
    sha256 = "215868e83c1213b4cca19595f82430001cae37d56a75a93face9a9768e8aa669"
    url = "https://github.com/JuliaBinaryWrappers/Arb_jll.jl/releases/download/Arb-v2.17.0+1/Arb.v2.17.0.x86_64-w64-mingw32.tar.gz"
